#if defined _logger_const_included
    #endinput
#endif
#define _logger_const_included

/*******************************************************************************
 * CONSTANTS
 ******************************************************************************/

/**
 * String representation of {@link #Invalid_Severity}
 */
stock const SEVERITY_INVALID_STRING[] = "INVALID";

/**
 * String representation of {@link #Severity_Highest}
 */
stock const SEVERITY_ALL_STRING[]     = "ALL";

/**
 * String representation of {@link #Invalid_Debug}
 */
stock const SEVERITY_DEBUG_STRING[]   = "DEBUG";

/**
 * String representation of {@link #Invalid_Info}
 */
stock const SEVERITY_INFO_STRING[]    = "INFO";

/**
 * String representation of {@link #Invalid_Warn}
 */
stock const SEVERITY_WARN_STRING[]    = "WARN";

/**
 * String representation of {@link #Invalid_Error}
 */
stock const SEVERITY_ERROR_STRING[]   = "ERROR";

/**
 * String representation of {@link #Severity_Lowest}
 */
stock const SEVERITY_NONE_STRING[]    = "NONE";